### ISSUE TITLE
Search with this extension takes to the number '2' of search result pages

### ISSUE THREAD

**Issue by fjvico** [piglovesyou/google-search-result-focusable#1]
Running on a Lubunto 16.04 distro, Chrome Version 69.0.3497.81 (Official Build) (64-bit), after the search, instead of the first search result, the highlighted result is the number '2', at the bottom of the results page, so if you hit Enter, you're taken to the second page of results. This has been verified across several Lubuntu 16.04 systems, even after reinstalling the extension, there's no way to take back the original functioning.
Some other times, it highlights the 'Images' link, which can be quite down in the results list.

**Comment by piglovesyou** [comment]
@fjvico Thank you for using the extension and issuing the problem. I can totally reproduce it in my Mac OS, Google Chrome Version 69.0.3497.100 (Official Build) (64-bit). I'll fix it soon.

**Comment by piglovesyou** [comment]
Please try 0.3.0 that fixes the DOM problem.
https://chrome.google.com/webstore/detail/hit-tab-and-enter-on-goog/kkldgaaaafjoipnomoinnkccihdiffee

**Comment by fjvico** [comment]
This seems to solve the problem. Extension up and running again. Thanks!
