### ISSUE TITLE
Feature Request: Go straight to Next Arrow On The Bottom Of The Page

### ISSUE THREAD

**Issue by seantdinh** [piglovesyou/google-search-result-focusable#14]
Thank you for this, it works. Not sure if you're able to do this but, once you get towards the bottom of the page, tab goes across each number of pages, making you tab through all of it to get to the next arrow. It'd be cool if it tabbed straight to next arrow

**Comment by piglovesyou** [comment]
Hi @seantdinh, thank you for the feedback. I thought it's a good idea though, there are several reasons I'd rather keep the current state.

* Focusing on the second "o" of the "Gooooooogle" is the same to focusing "Next", so it's not meant users get the extra operation 
* I'd like to keep the extension as simple as possible, just following spec of the Google's result page, without extra logic
* As long as Google keeps "Gooooooogle" links, I think we should follow the order of the links

**Comment by seantdinh** [comment]
Understood! Thank you again 😊
