### ISSUE TITLE
Hit TAB and ENTER not working on Brave

### ISSUE THREAD

**Issue by fjvico** [piglovesyou/google-search-result-focusable#2]
The behavior is not as expected (i.e. like in Chrome) for Brave version 0.66.99 Chromium: 75.0.3770.100 (Official Build) (64-bit), running on Lubuntu 18.04. First TAB hit would take to a hidden button in the top-right corner, labelled "Skip to main content", not to first result.

**Comment by piglovesyou** [comment]
Hi, thanks for reporting. Just for the record, Google Chrome `Version 75.0.3770.100 (Official Build) (64-bit)` on MacOS `10.14.5 (18F132)`works fine now.

**Comment by piglovesyou** [comment]
Closing.
